### ISSUE TITLE
A Pi-Hole with Comcast

### ISSUE THREAD

**Issue by theJollySin** [theJollySin/thejollysin.github.io#90]
Try it out, and see how it goes.

* [Pi-Hole.net](https://pi-hole.net/)
  * [Pi-Hole.net blog](https://pi-hole.net/blog/)
* [Comcast router trubs](https://www.reddit.com/r/pihole/comments/8c8xiw/comcast_router_will_not_let_me_change_my_primary/)
* [Comcast router issues](https://www.reddit.com/r/pihole/comments/515t4p/comcastxfinity_router/)
* [Subreddit](https://old.reddit.com/r/pihole/)
* [Instructables How-To](https://www.instructables.com/id/Pi-Hole/)
* [AdaFruit how-to](https://learn.adafruit.com/pi-hole-ad-blocker-with-pi-zero-w/install-pi-hole)
* [Pi-Hole on Windows how-to](https://thatservernerd.com/2016/10/18/pi-hole-how-to-block-all-ads-on-every-device-in-your-network-and-integrate-with-your-windows-active-directory/)
* [Nice YouTube from "Know How"](https://www.youtube.com/watch?v=-1m_nGNUglM)

**Comment by mwoolweaver** [comment]
Out of curiosity did you manage to figure out dhcp & dns settings on the Comcast equipment?

**Comment by theJollySin** [comment]
@mwoolweaver Actually, I gave up. I know someone that got it working in like 5 minutes. But everything I tried was blocked in some way or another.  There is still a Raspberry Pi and keyboard sitting under my TV, and I would like to give it a second attempt. But I think the problem is I need to better understand these little all-in-one routers that Comcast gives everyone. 

Sorry.

**Comment by mwoolweaver** [comment]
From what I can tell you can only use the pi-hole for dns and you can’t use it’s dhcp function because the all-in-one router they send you won’t allow you to disable dhcp. 


Also to take this a step further, the only way to guarantee that all dns traffic is routed through the pi-hole is to obtain a separate wireless router and put the all-in-one from Comcast in bridge mode and then disable the dhcp function in the separate router and let the pi-hole handle all dns and dhcp for your network. 

This was the conclusion I came to in the last 2 days.

**Comment by theJollySin** [comment]
I think my problem is either (a) just navigating the awful menus on this Comcast all-in-one router, or (b) there are things I don't know about networking that keep me from understanding some part of those menus.

**Comment by theJollySin** [comment]
I think my problem is either (a) just navigating the awful menus on this Comcast all-in-one router, or (b) there are things I don't know about networking that keep me from understanding some part of those menus.
